'''
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
'''

def Fibonacci(n):
    if (n < 0):
        return 0
    if (n == 1 or n == 2):
        return 1
    else:
        return Fibonacci(n-1) + Fibonacci(n-2)
    
evenValued = []
count = 0
while True:
    nextValue = Fibonacci(count)
    if nextValue % 2 == 0 and nextValue < 4000000:
        evenValued.append(nextValue)

    if nextValue > 4000000:
        break
    count += 1

print(sum(evenValued))
